export const DUMMY_TASKS = [
  {
    id: 't1',
    userId: 'u1',
    title: 'Master Angular',
    summary:
      'Learn all the basic and advanced features of Angular & how to apply them.',
    dueDate: '2025-12-31',
  },
  {
    id: 't2',
    userId: 'u3',
    title: 'Build first prototype',
    summary: 'Build a first prototype of the online shop website',
    dueDate: '2024-05-31',
  },
  {
    id: 't3',
    userId: 'u3',
    title: 'Prepare issue template',
    summary:
      'Prepare and describe an issue template which will help with project management',
    dueDate: '2024-06-15',
  },
  {
    id: 't4',
    userId: 'u1',
    title: 'Complete React course',
    summary: 'Finish the online React course and practice building projects.',
    dueDate: '2025-03-20',
  },
  {
    id: 't7',
    userId: 'u4',
    title: 'Database schema design',
    summary: 'Design the database schema for the new microservice.',
    dueDate: '2024-07-25',
  },
  {
    id: 't8',
    userId: 'u4',
    title: 'Code review checklist',
    summary: 'Develop a checklist to ensure high-quality code reviews.',
    dueDate: '2024-09-01',
  },
  {
    id: 't9',
    userId: 'u5',
    title: 'UI/UX audit',
    summary: 'Perform an audit of the current UI and suggest improvements.',
    dueDate: '2024-10-14',
  },
  {
    id: 't10',
    userId: 'u5',
    title: 'Set up CI/CD pipeline',
    summary: 'Automate builds and deployments using GitHub Actions.',
    dueDate: '2025-02-01',
  },
  {
    id: 't11',
    userId: 'u3',
    title: 'Customer feedback analysis',
    summary: 'Analyze survey results to improve product features.',
    dueDate: '2024-08-18',
  },
  {
    id: 't13',
    userId: 'u4',
    title: 'Security audit',
    summary: 'Run a complete audit of app security vulnerabilities.',
    dueDate: '2025-04-10',
  },
  {
    id: 't14',
    userId: 'u1',
    title: 'Deploy demo app',
    summary: 'Deploy the demo app to a staging environment for client review.',
    dueDate: '2024-06-30',
  },
  {
    id: 't15',
    userId: 'u5',
    title: 'Marketing strategy plan',
    summary: 'Collaborate with marketing to draft the new launch strategy.',
    dueDate: '2025-05-15',
  },
  {
    id: 't17',
    userId: 'u3',
    title: 'Team retrospective',
    summary: 'Organize and lead the monthly retrospective meeting.',
    dueDate: '2024-06-28',
  },
  {
    id: 't18',
    userId: 'u4',
    title: 'Docker setup guide',
    summary: 'Write a guide for setting up development environments with Docker.',
    dueDate: '2024-09-22',
  },
  {
    id: 't19',
    userId: 'u5',
    title: 'Accessibility improvements',
    summary: 'Ensure all pages meet WCAG accessibility standards.',
    dueDate: '2024-12-12',
  },
  {
    id: 't20',
    userId: 'u1',
    title: 'GraphQL API integration',
    summary: 'Integrate GraphQL endpoints into the frontend.',
    dueDate: '2025-03-01',
  },
];
